version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env     # 👈 This is the correct path
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npx nodemon index.js

  extractor:
    build: ./extractor
    ports:
      - "8000:8000"
