version: "3.8"
services:
  backend:
    build: .
    container_name: tax_automation
    ports:
      - "5000:5000"
    networks:
      - tax_net
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - tax_net

networks:
  tax_net:
    driver: bridge
