// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjqezbfqmwfwbutgzwqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcWV6YmZxbXdmd2J1dGd6d3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTEzODUsImV4cCI6MjA1OTM2NzM4NX0.8i9Iws3d3STiftVM_BpVBTkKJ1cpzzUId36BnorQRdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);